- R/Downsample.Matrix.R
- inst/shiny/server.R
- inst/shiny/ui.R
- singleCellTK-master.Rproj
Really, this should be pulled into a development branch instead of master at this point, but I can't create new compbiomed branches.
> Introduction of subsampling tab

- inst/shiny/server.R
- inst/shiny/ui_08_mast.R
conditional selection of the interested factor for shiny mast
> conditional selection of the interested factor for shiny mast

- R/MAST_plot_functions.R
- inst/shiny/server.R
- inst/shiny/ui.R
- man/MASTviolin.Rd
Similar updates to liner model plot function still need to be made, as well as opening more options to user on the shiny side
> Updates to Violin plot function

- .travis.yml
- DESCRIPTION
- R/MAST.R
- inst/shiny/server.R
- inst/shiny/ui_03_cluster.R
- inst/shiny/ui_04_diffex.R
- inst/shiny/ui_08_mast.R
- man/MAST.Rd
* ability to model cdr, run thresholding and choose to use them in the model
> Updates to MAST Functionality

- DESCRIPTION
- inst/shiny/ui.R
- inst/shiny/ui_01_upload.R
> Navbar page titles changed

- R/scDiffEx.R
- tests/testthat/test-MAST.R
- tests/testthat/test-diffex.R
Added same error message if data has NAs to the diff ex function as with the MAST function, created a test case, and cleaned up the test case for the MAST file.
> Diff Ex Error Message

- R/importOptimus.R
> Optimus import function

- R/seuratFunctions.R
- inst/shiny/server.R
- inst/shiny/ui.R
- inst/shiny/ui_08_seurat.R
Added seuratFunctions.R file (seurat wrapper/helper functions)
Added ui_08_seurat.R file (ui for seurat workflow)
Updated server.R to include new observe events for seurat workflow
Updated ui.R to include the page 8 i.e. ui_08_seurat.R
> Added seurat workflow

- R/importDropEst.R
- includes option to hold matrix in delayedArray format
- Cleaning up comments
- Standardizing documentation
> import dropEst funcion 

- R/seuratFunctions.R
- inst/shiny/server.R
- inst/shiny/ui_01_upload.R
- inst/shiny/ui_09_2_seuratWorkflow.R
- Added seurat object radio button in upload ui
- Added support for custom assays in seurat workflow (from sce)
- Renamed sce with inSCE for consistent formatting
- Replaced 1:n in for loops with seq()
- Replaced multiple reactive objects with a single "seuratWorkflow" reactive values object that now contains all reactive values to be used in the workflow
- Removed input/output form seurat workflow
> Added support for uploading seurat objects and updated seurat workflow to include support for custom assays from sce

- R/dropletUtils_barcodeRank.R
- R/dropletUtils_emptyDrops.R
- R/scds_doubletdetection.R
- R/scrublet_doubletDetection.R
All functions should be re-tested.
The current code does not store Scrublet version in metadata.
> Storing current function parameters and package version in sce metadata 

- R/MASTPlotFunctions.R
- R/runMAST.R
- inst/shiny/server.R
- inst/shiny/ui.R
- inst/shiny/ui_05_2_mast.R
MAST DE UI is updated here. All basic functions are usable. 
More optional adjustments for plots and the find-marker page will be the next.
* "diff" from the to .R scripts looks covering the two whole files, but actually only a few lines were modified. I guess probably it is because of a "file format" change from "dos" to "unix".
> MAST DE basic

- DESCRIPTION
- R/HtmlExport.R
- inst/rmarkdown/qc/BarcodeRankDrops.Rmd
- inst/rmarkdown/qc/Bcds.Rmd
- inst/rmarkdown/qc/CellQC.Rmd
- inst/rmarkdown/qc/Cxds.Rmd
- inst/rmarkdown/qc/CxdsBcdsHybrid.Rmd
- inst/rmarkdown/qc/DecontX.Rmd
- inst/rmarkdown/qc/DoubletCells.Rmd
- inst/rmarkdown/qc/DoubletFinder.Rmd
- inst/rmarkdown/qc/DropletQC.Rmd
- inst/rmarkdown/qc/EmptyDrops.Rmd
- inst/rmarkdown/qc/QCMetrics.Rmd
- inst/rmarkdown/qc/Scrublet.Rmd
1. HtmlExport.R contains getHtmlReportDropletQC(), getHtmlReportCellQC(), getHtmlReportPerQC() functions to render .Rmd reports into .html file;
2. inst/rmarkdown/qc folder contains .Rmd templates.
> Reports code

- inst/rmarkdown/qc/BarcodeRankDrops.Rmd
- inst/rmarkdown/qc/Bcds.Rmd
- inst/rmarkdown/qc/CellQC.Rmd
- inst/rmarkdown/qc/Cxds.Rmd
- inst/rmarkdown/qc/CxdsBcdsHybrid.Rmd
- inst/rmarkdown/qc/DecontX.Rmd
- inst/rmarkdown/qc/DoubletCells.Rmd
- inst/rmarkdown/qc/DoubletFinder.Rmd
- inst/rmarkdown/qc/DropletQC.Rmd
- inst/rmarkdown/qc/EmptyDrops.Rmd
- inst/rmarkdown/qc/QCMetrics.Rmd
- inst/rmarkdown/qc/Scrublet.Rmd
Added Droplet QC reports wrapper functions, updated QC reports descriptions functions
> Report updates

- R/decorate.R
- inst/shiny/helpers.R
- inst/shiny/server.R
- inst/shiny/styles.CSS
- inst/shiny/ui.R
* updated withConsoleRedirect(). All console outputs from importExampleData get sent to the shiny UI console.
> Updated console logging to include messages (errors, warnings, etc)

- R/miscFunctions.R
- R/seuratFunctions.R
- inst/shiny/server.R
- inst/shiny/ui_01_columnAnnotation.R
- inst/shiny/ui_01_rowAnnotation.R
- Added a function inside miscFunctions.R to keep the datatypes of row/col annotation intact
- Added checks to make sure that row/col annotation editor does not populate ui when row/col data is absent
- Fixed a bug that was causing "PCA", "tSNE" and "UMAP" computation to crash in dimensionality reduction tab
- Integrated changes suggested from previous pull request
- Update/refactor .manageDataTypes() function
> Some updates to col/row annotation editor and fixed some bugs

- DESCRIPTION
- Dockerfile
- inst/shiny/ui_01_columnAnnotation.R
- inst/shiny/ui_01_rowAnnotation.R
- inst/shiny/ui_02_qc_filter.R
- inst/shiny/ui_04_batchcorrect.R
This will allow you to run the app as a docker container, which is a prerequisite for ShinyProxy. Compilation can/will take multiple hours because R does not publish binaries for Linux for v3.6. This recently changed with R 4 and their new package manager, but Celda wouldn't compile because of a missing igraph .so file. It's worth it to try to get this to work because building the docker image is so much faster with pre-built binaries.
> Add docker build

- R/ggPerQCWrapper.R
- R/ggPlotting.R
- man/runDoubletCells.Rd
Making modifications to combination function, can now adjust the position of labels
> Modifications to combination function

- DESCRIPTION
- R/ggPerQCWrapper.R
- R/ggPlotting.R
- man/dot-ggScatter.Rd
- man/plotBarcodeRankScatter.Rd
- man/plotBcdsResults.Rd
- man/plotCxdsResults.Rd
- man/plotDecontXResults.Rd
- man/plotDoubletCellsResults.Rd
- man/plotDoubletFinderResults.Rd
- man/plotEmptyDropsResults.Rd
- man/plotEmptyDropsScatter.Rd
- man/plotRunPerCellQCResults.Rd
- man/plotSCEDensity.Rd
- man/plotSCEDensityAssayData.Rd
- man/plotSCEDensityColData.Rd
- man/plotSCEDimReduceColData.Rd
- man/plotSCEDimReduceFeatures.Rd
- man/plotSCEScatter.Rd
- man/plotSCEViolin.Rd
- man/plotSCEViolinAssayData.Rd
- man/plotSCEViolinColData.Rd
- man/plotScdsHybridResults.Rd
- man/plotScrubletResults.Rd
Fixes to bug that was causing plotViolin functions to output lists of text instead of a .ggplot object.
> Additional bug fixes relevant to ggSCTKCombinePlots function

- inst/shiny/server.R
- inst/shiny/ui_04_fs_dimred.R
- Fixed some bugs
- Removed redundant conditions that caused errors
- Added some checks
> Fixed bugs in Dimensionality Reduction tab

- DESCRIPTION
- NEWS
Updates to NEWS to document updates to the singleCellTK package
Updates to DESCRIPTION, authors added
> Documentation update

- R/importMultipleSources.R
- exec/SCTK_runQC_Documentation2.md
1. Fix bugs in importMultipleSources.R
2. Update QC documentation
> Fix bugs in importMultipleSources.R. Update QC documentation

- R/miscFunctions.R
- R/seuratFunctions.R
- inst/shiny/server.R
- inst/shiny/ui_09_2_seuratWorkflow.R
- man/seuratFindMarkers.Rd
- Added custom filters in seuratFindMarkers
- Added a filter utility function
- Returned table is now same across all seuratFindMarker functions
- Removed spinner from visualizations (as it disabled resizable panel)
- Fixed other UI bugs
> Major updates to seuratFindMarker tab

- R/seuratFunctions.R
- man/seuratComputeHeatmap.Rd
- man/seuratElbowPlot.Rd
- man/seuratGenePlot.Rd
- Added some additional parameters to seurat functions to support same workflow as the seurat report file, for example, addition of custom colors in featurePlot etc.
> Minor additions to seurat functions

- R/seuratFunctions.R
- inst/rmarkdown/seurat/SeuratReport.Rmd
- inst/shiny/server.R
- inst/shiny/ui_09_2_seuratWorkflow.R
- man/seuratReductionPlot.Rd
- Fixed bugs in seuratReport.Rmd markdown and the seuratReport() function
- Fixed a bug in delete data tab reported by Yichen
- Fixed a bug reported by Yichen and Caroline that caused seuratReductionPlots to give error when the metadata of the input seurat object as NA values
- Added cluster labels in seurat UI
- SeuratReport output object now fully compatible with seurat ui
> Fixed various bugs

- .gitignore
- R/enrichRSCE.R
- _pkgdown.yml
- inst/shiny/ui.R
- inst/shiny/ui_01_columnAnnotation.R
- inst/shiny/ui_01_gene_sets.R
- inst/shiny/ui_01_import.R
- inst/shiny/ui_01_removeData.R
- inst/shiny/ui_01_rowAnnotation.R
- inst/shiny/ui_02_filter.R
- inst/shiny/ui_02_qc.R
- inst/shiny/ui_02_qc_filter.R
- inst/shiny/ui_03_2_cluster.R
- inst/shiny/ui_04_batchcorrect.R
- inst/shiny/ui_04_fs_dimred.R
- inst/shiny/ui_05_1_diffex.R
- inst/shiny/ui_05_2_findMarker.R
- inst/shiny/ui_05_3_cellTypeLabel.R
- inst/shiny/ui_06_1_pathway.R
- inst/shiny/ui_06_2_enrichR.R
- inst/shiny/ui_07_subsample.R
- inst/shiny/ui_08_2_cellviewer.R
- inst/shiny/ui_08_3_heatmap.R
- inst/shiny/ui_09_2_seuratWorkflow.R
- inst/shiny/ui_09_3_celdaWorkflow.R
- inst/shiny/ui_export.R
- man/enrichRSCE.Rd
Updated all links in UI. 
While working on this, some missing documentation was found:
- cell type labeling
- sample size calculator
- celda curated workflow
Added links for these pages in the UI, and we should update the corresponding docs soon and make sure the final paths/names of them match the links in UI. 
Additionally, there are existing pages without a pkgdown redirection link in the head navbar. Added some of them and the whole site need to be rebuilt. Since @rz2333 has made some updates in his pull request. I'll have another push for the rebuilt site after his PR is accepted.
> Devel - UI links

- Dockerfile
- inst/rmarkdown/seurat/SeuratReport.Rmd
- inst/shiny/module_nonLinearWorkflow.R
- inst/shiny/server.R
- inst/shiny/ui_02_qc_filter.R
- renv_R4.0.lock
A newer version of Seurat has changed the output dataframe slightly which now as a column for log-fold change named as avg_log2FC instead of avg_logFC.
> Fixed a minor bug in seuratFindMarkers user-interface

- inst/shiny/server.R
- inst/shiny/ui_03_2_cluster.R
- inst/shiny/ui_04_batchcorrect.R
- inst/shiny/ui_05_1_diffex.R
- inst/shiny/ui_05_2_findMarker.R
UI updates for the plotting regions in:
- Batch Correction
- Clustering
- Differential Expression
- Find Marker
Together with the use of `isolate()` function
> Devel: UI updates

- exec/SCTK_runQC.R
- inst/rmarkdown/qc/CellQC.Rmd
- inst/rmarkdown/qc/DropletQC.Rmd
Update link in QC report. 
Fix minor bug in SCTK_runQC.R about the argument --split
> Update link in QC report. Fix minor bug in SCTK_runQC.R

- R/ggPerQCWrapper.R
- inst/rmarkdown/qc/CellQC.Rmd
Minor edits/bug fixes to CellQC.Rmd
- Now showing violin plots for gene subsets imported within SCE
- Will not show plot tab if gene subset not used (and thus plot not generated)
> Modifications to CellQC.Rmd

- vignettes/articles/cmd_qc.Rmd
change F to FALSE in cmd_qc.Rmd.
> change F to FALSE in cmd_qc.Rmd

- R/scds_doubletdetection.R
Minor bug fix, add if statement (` if (estNdbl)`) for factor conversion of doublet calls when doublet estimation is turned on.
> Bug fix, scds_doubletdetection.R

- inst/shiny/ui_09_3_celdaWorkflow.R
Encountered this error when I merged from `compbiomed/singleCellTK@devel`. Should be merged quickly if nobody else has already been working on this. Or please point me out if it's working fine on your end but I missed something. @joshua-d-campbell @irzamsarfraz @salzcamino @npervaiz
> Urgent: Fix celda UI incomplete parentheses problem

- R/getTopHVG.R
- R/scanpyFunctions.R
- man/getTopHVG.Rd
Modified getTopHVG function to work for scanpy
> getTopHVG modification

- R/importMultipleSources.R
- inst/shiny/server.R
- inst/shiny/ui_01_import.R
- Add ui and backend logic to import samples from multiple pipelines using file selectors instead of directories
- Fixed issue #688
> Updates to sample import

- R/exportSCEtoAnndata.R
- R/sce2adata.R
- exec/SCTK_runQC.R
Fixes:
-temporary workaround for the SCE to AnnData export bug where reticulate-called Python dunder setters fail
-a more permanent solution involving only zellkonverter is in the works once zellkonverter can handle the same problem
Others:
-commented out but kept old code in case anyone needs it for reference
-made note of future depreciated functions once zellkonverter works fully
> Fixed AnnData export bug

- Dockerfile
Edits:
-Dockerfile now correctly points to master instead of 2.10.1 or devel for people building the Docker image locally using the provided Dockerfile
> Edited Dockerfile to point to master

- R/runGSVA.R
- R/seuratFunctions.R
Fixed Seurat and GSVA functions
**Todo: Must fix a failing unit test with runGSVA**
> prep for BioC release

- DESCRIPTION
- R/runGSVA.R
- tests/testthat/test-pathway.R
Added GSVA version requirement, fixed one bug in runGSVA call, added explicit parameters in unit tests.
> more GSVA fixes

- DESCRIPTION
PR covers:
-last few fixes as noted in the previous PR
-redundancy in DESCRIPTION file
-fixes to documentation
> Fixed all failing tests

- R/plotSCEHeatmap.R
Added package imports that now removes NOTES
> Fixes Notes and other warnings

- R/scDblFinder_doubletDetection.R
- man/runScDblFinder.Rd
Sets the BPPARAM RNGseed default value as the seed value in thhe runScDblFinder function
> runScDblFinder seed
